[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font"
style = "Italic"

[font.lyph_offset]
x = 0
y = 0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
program = "/bin/fish"

[window]
dynamic_padding = false

[window.padding]
x = 8
y = 8
